# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26b83bebccf3622c9230789230110fa1f04b54ef25d507141f0c1d52ff27e93dab4a80538ecf7cd98060508740f400fbe4b23d0c3039daa0d7f2bb12381b9ff

test:
  secret_key_base: fa558b8be3e4f84a920c4ca92125617f34006c7f77a79f5ffd3850b1a2fa868e4306d3ccf86bc902a5a4f476c45bec9f5fbb09e7e8254f43fb63d7b9ebc3b835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
